name: Events 
on: 
  pull_request:
    types:
      - opened
      - syncronized
    branches:
      - main
jobs:
  events-jobs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "When PR Created"
