name: Repository Event
run-name: ${{github.actor}}
on:  
  pull_request_review:
    types: [submitted, edited, dismissed]
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tested for the PR Review"
      
