name: Repository Event
run-name: ${{github.actor}}
on:  
  pull_request_review:
    types: [submitted, edited, dismissed]
jobs:
  approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      
